require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AremanagersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Aremanager. As you add validations to Aremanager, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AremanagersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aremanagers as @aremanagers" do
      aremanager = Aremanager.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:aremanagers)).to eq([aremanager])
    end
  end

  describe "GET show" do
    it "assigns the requested aremanager as @aremanager" do
      aremanager = Aremanager.create! valid_attributes
      get :show, {:id => aremanager.to_param}, valid_session
      expect(assigns(:aremanager)).to eq(aremanager)
    end
  end

  describe "GET new" do
    it "assigns a new aremanager as @aremanager" do
      get :new, {}, valid_session
      expect(assigns(:aremanager)).to be_a_new(Aremanager)
    end
  end

  describe "GET edit" do
    it "assigns the requested aremanager as @aremanager" do
      aremanager = Aremanager.create! valid_attributes
      get :edit, {:id => aremanager.to_param}, valid_session
      expect(assigns(:aremanager)).to eq(aremanager)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Aremanager" do
        expect {
          post :create, {:aremanager => valid_attributes}, valid_session
        }.to change(Aremanager, :count).by(1)
      end

      it "assigns a newly created aremanager as @aremanager" do
        post :create, {:aremanager => valid_attributes}, valid_session
        expect(assigns(:aremanager)).to be_a(Aremanager)
        expect(assigns(:aremanager)).to be_persisted
      end

      it "redirects to the created aremanager" do
        post :create, {:aremanager => valid_attributes}, valid_session
        expect(response).to redirect_to(Aremanager.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aremanager as @aremanager" do
        post :create, {:aremanager => invalid_attributes}, valid_session
        expect(assigns(:aremanager)).to be_a_new(Aremanager)
      end

      it "re-renders the 'new' template" do
        post :create, {:aremanager => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested aremanager" do
        aremanager = Aremanager.create! valid_attributes
        put :update, {:id => aremanager.to_param, :aremanager => new_attributes}, valid_session
        aremanager.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested aremanager as @aremanager" do
        aremanager = Aremanager.create! valid_attributes
        put :update, {:id => aremanager.to_param, :aremanager => valid_attributes}, valid_session
        expect(assigns(:aremanager)).to eq(aremanager)
      end

      it "redirects to the aremanager" do
        aremanager = Aremanager.create! valid_attributes
        put :update, {:id => aremanager.to_param, :aremanager => valid_attributes}, valid_session
        expect(response).to redirect_to(aremanager)
      end
    end

    describe "with invalid params" do
      it "assigns the aremanager as @aremanager" do
        aremanager = Aremanager.create! valid_attributes
        put :update, {:id => aremanager.to_param, :aremanager => invalid_attributes}, valid_session
        expect(assigns(:aremanager)).to eq(aremanager)
      end

      it "re-renders the 'edit' template" do
        aremanager = Aremanager.create! valid_attributes
        put :update, {:id => aremanager.to_param, :aremanager => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aremanager" do
      aremanager = Aremanager.create! valid_attributes
      expect {
        delete :destroy, {:id => aremanager.to_param}, valid_session
      }.to change(Aremanager, :count).by(-1)
    end

    it "redirects to the aremanagers list" do
      aremanager = Aremanager.create! valid_attributes
      delete :destroy, {:id => aremanager.to_param}, valid_session
      expect(response).to redirect_to(aremanagers_url)
    end
  end

end
